spring:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/defender
server:
  port: ${PORT:8080}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: x-forwarded-port
  compression:
    enabled: true

---

spring:
  profiles: docker
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
server:
  tomcat:
    remote-ip-header: x-real-ip

---

spring:
  profiles: heroku
  datasource:
    url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=disable
    username: ${PGUSER}
    password: ${PGPASSWORD}