services:
  - docker

env:
  global:
    - WEB_IMAGE=quantasnet/defender-web
    - API_IMAGE=quantasnet/defender-api

script:
  - docker build -t ${API_IMAGE} .
  - cd defender-client
  - docker build -t ${WEB_IMAGE} .

after_script:
  - docker images

