version: '3.5'

services:
  defender-api:
    build:
      context: defender-api/.devcontainer/.
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    environment:
      PORT: 8080
      TZ: America/Chicago
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://defender-db:5432/defender?sslmode=disable
      DATABASE_USER: defender
      DATABASE_PASSWORD: defender
    networks:
      - defender
  defender-client:
    build:
      context: defender-client/.devcontainer/.
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    networks:
      - defender
  defender-db:
    image: postgres:9.4
    networks:
      - defender
    environment:
      TZ: America/Chicago
      POSTGRES_PASSWORD: defender
      POSTGRES_USER: defender
      POSTGRES_DB: defender

networks:
  defender: