version: "3"

services:

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - defender
    environment:
      POSTGRES_PASSWORD: defender
      POSTGRES_USER: defender
      POSTGRES_DB: defender

  defender-web:
    image: quantasnet/defender-web:0.0.1-SNAPSHOT
    build:
      context: defender-client/.
    networks:
      - defender
    links:
      - "defender-api:defender-api"
    ports:
      - 8080:80
    environment: 
      API_HOST: defender-api
      API_PORT: 8080

  defender-api:
    image: quantasnet/defender-api:0.0.1-SNAPSHOT
    build:
      context: .
    restart: always
    networks:
      - defender
    links:
      - "db:database"
    healthcheck:
      test: ["CMD", "/bin/sh", "-c",  "wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      PORT: 8080
      TZ: America/Chicago
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:postgresql://database:5432/defender?sslmode=disable
      DATABASE_USER: defender
      DATABASE_PASSWORD: defender

networks:
  defender:

volumes:
  db-data: