apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  database-password: defender
  database-user: defender
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database-password
        - name: POSTGRES_DB
          value: defender
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defender-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defender-api
  template:
    metadata:
      labels:
        app: defender-api
    spec:
      containers:
      - name: defender-api
        image: quantasnet/defender-api:master
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: database-password
        - name: TZ
          value: America/Chicago
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/defender?sslmode=disable
        - name: AUTH_STS_SERVER
          value: <STS URL>
        - name: AUTH_CLIENT_ID
          value: <XXXXXXXXXXXXXXXXXXXXXXXX>
---
apiVersion: v1
kind: Service
metadata:
  name: defender-api
spec:
  selector:
    app: defender-api
  ports:
  - port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defender-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defender-client
  template:
    metadata:
      labels:
        app: defender-client
    spec:
      containers:
      - name: defender-client
        image: quantasnet/defender-client:master
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: TZ
          value: America/Chicago
---
apiVersion: v1
kind: Service
metadata:
  name: defender-client
spec:
  selector:
    app: defender-client
  ports:
  - port: 80
  type: NodePort