version: "3"

services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 9080:8080
    networks:
      - defender_defender
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

networks:
  defender_defender:
    external: true